[package]
name = "turbomcpstudio"
version = "0.1.0"
description = "TurboMCP Studio - Native desktop application for Model Context Protocol development"
authors = ["TurboMCP Studio Team"]
edition = "2021"

[lib]
name = "turbomcpstudio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
# Tauri core
tauri = { version = "2.0", features = [] }
tauri-plugin-opener = "2.0"
tauri-plugin-shell = "2.0"
tauri-plugin-sql = { version = "2.0", default-features = false, features = ["sqlite"] }
tauri-plugin-fs = "2.0"
tauri-plugin-process = "2.0"
tauri-plugin-dialog = "2.0"
tauri-plugin-http = "2.0"
tauri-plugin-clipboard-manager = "2.3"

# Plugin system
tauri-plugin-single-instance = "2.0"
tauri-plugin-window-state = "2.0"
tauri-plugin-os = "2.0"

# HTTP client for LLM API requests
reqwest = { version = "0.12", features = ["json"] }

# LLM Provider SDKs
async-openai = "0.30"  # Official OpenAI SDK for Rust

# TurboMCP integration - v2.0.2 (stable)
turbomcp = "2.0.2"
turbomcp-client = "2.0.2"
# turbomcp-transport is defined in target-specific sections below
turbomcp-protocol = "2.0.2"

# Async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"  # For Docker MCP registry YAML parsing

# Data structures
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.0"
url = "2.5"  # URL parsing for HTTP transport

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Database
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "chrono", "uuid"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Process management
sysinfo = "0.32"

# File & path utilities
dirs = "5.0"

# Concurrency
parking_lot = "0.12"
dashmap = "6.1"

# Secure storage
keyring = "2.3"
tauri-plugin-log = "2.7.0"
log = "0.4.28"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
# Unix socket support on Linux and macOS
turbomcp-transport = { version = "2.0.2", features = ["stdio", "http", "websocket", "tcp", "unix", "compression", "tls"] }

[target.'cfg(target_os = "windows")'.dependencies]
# Exclude unix feature on Windows
turbomcp-transport = { version = "2.0.2", features = ["stdio", "http", "websocket", "tcp", "compression", "tls"] }

[features]
default = ["stdio", "http", "websocket", "tcp", "plugins"]
stdio = []
http = []
websocket = []
tcp = []
unix = []
plugins = []  # Plugin system support for TurboMCP 1.0.9+
full = ["stdio", "http", "websocket", "tcp", "plugins"]  # All features for production

